import React, { useState } from 'react';
import { motion, AnimatePresence } from 'motion/react';
import { 
  ArrowLeft, 
  Clock, 
  FileText, 
  Zap, 
  HelpCircle, 
  Share2, 
  Download,
  Play,
  CheckCircle2,
  AlertTriangle,
  ChevronRight,
  MessageSquare
} from 'lucide-react';
import { Lecture } from '../types';
import { cn } from '../lib/utils';
import ReactMarkdown from 'react-markdown';
import remarkGfm from 'remark-gfm';
import remarkMath from 'remark-math';
import rehypeKatex from 'rehype-katex';
import 'katex/dist/katex.min.css';

interface LectureViewProps {
  lecture: Lecture;
  onBack: () => void;
}

export default function LectureView({ lecture, onBack }: LectureViewProps) {
  const [activeTab, setActiveTab] = useState<'notes' | 'flashcards' | 'quiz' | 'transcript'>('notes');

  const handleShareWhatsApp = () => {
    const text = `*LectureMind AI Summary: ${lecture.title}*\n\n${lecture.summary}\n\nSubject: ${lecture.subject}\n\nGenerated by LectureMind AI`;
    window.open(`https://wa.me/?text=${encodeURIComponent(text)}`, '_blank');
  };

  const getEmbedUrl = (url?: string) => {
    if (!url) return null;
    const regExp = /^.*(youtu.be\/|v\/|u\/\w\/|embed\/|watch\?v=|\&v=)([^#\&\?]*).*/;
    const match = url.match(regExp);
    return (match && match[2].length === 11) ? `https://www.youtube.com/embed/${match[2]}` : null;
  };

  const embedUrl = getEmbedUrl(lecture.videoUrl);

  return (
    <motion.div 
      initial={{ opacity: 0, x: 20 }}
      animate={{ opacity: 1, x: 0 }}
      exit={{ opacity: 0, x: -20 }}
      className="max-w-5xl mx-auto"
    >
      <button 
        onClick={onBack}
        className="flex items-center gap-2 text-gray-400 hover:text-white mb-8 transition-colors group"
      >
        <ArrowLeft className="w-5 h-5 group-hover:-translate-x-1 transition-transform" />
        Back to Dashboard
      </button>

      {embedUrl && (
        <div className="aspect-video w-full rounded-3xl overflow-hidden border border-white/10 mb-12 shadow-2xl">
          <iframe 
            src={embedUrl}
            className="w-full h-full"
            allow="accelerometer; autoplay; clipboard-write; encrypted-media; gyroscope; picture-in-picture"
            allowFullScreen
          />
        </div>
      )}

      <div className="flex flex-col lg:flex-row gap-8 mb-12">
        <div className="flex-1">
          <div className="flex items-center gap-3 mb-4">
            <span className={cn(
              "px-3 py-1 rounded-full text-xs font-bold uppercase tracking-widest",
              lecture.subject === 'Physics' ? "bg-blue-500/20 text-blue-400" :
              lecture.subject === 'Chemistry' ? "bg-orange-500/20 text-orange-400" :
              lecture.subject === 'Biology' ? "bg-green-500/20 text-green-400" :
              lecture.subject === 'Mathematics' ? "bg-purple-500/20 text-purple-400" :
              "bg-gray-500/20 text-gray-400"
            )}>
              {lecture.subject}
            </span>
            <span className="text-gray-500 text-sm flex items-center gap-1.5">
              <Clock className="w-4 h-4" />
              {lecture.createdAt?.toDate().toLocaleDateString()}
            </span>
          </div>
          <h1 className="text-4xl font-bold mb-6 tracking-tight">{lecture.title}</h1>
          
          <div className="bg-white/5 border border-white/10 rounded-3xl p-6 mb-8">
            <h3 className="text-indigo-400 font-bold uppercase text-xs tracking-widest mb-3">AI Summary</h3>
            <p className="text-gray-300 leading-relaxed">{lecture.summary}</p>
          </div>

          <div className="flex flex-wrap gap-3">
            <button 
              onClick={handleShareWhatsApp}
              className="flex items-center gap-2 px-6 py-3 bg-[#25D366]/10 text-[#25D366] rounded-2xl font-semibold hover:bg-[#25D366]/20 transition-all"
            >
              <Share2 className="w-5 h-5" />
              Share to WhatsApp
            </button>
            <button className="flex items-center gap-2 px-6 py-3 bg-white/5 text-white rounded-2xl font-semibold hover:bg-white/10 transition-all">
              <Download className="w-5 h-5" />
              Export PDF
            </button>
          </div>
        </div>

        <div className="lg:w-80 space-y-6">
          <div className="bg-[#141414] border border-white/5 rounded-3xl p-6">
            <h3 className="font-bold mb-4 flex items-center gap-2">
              <Clock className="w-5 h-5 text-indigo-400" />
              Key Topics
            </h3>
            <div className="space-y-4">
              {lecture.keyTopics?.map((topic, i) => (
                <div key={i} className="flex gap-3 group cursor-pointer">
                  <span className="text-xs font-mono text-indigo-400 bg-indigo-400/10 px-2 py-1 rounded h-fit">
                    {topic.timestamp}
                  </span>
                  <p className="text-sm text-gray-400 group-hover:text-white transition-colors">{topic.topic}</p>
                </div>
              ))}
            </div>
          </div>

          {lecture.doubts && lecture.doubts.length > 0 && (
            <div className="bg-amber-500/5 border border-amber-500/20 rounded-3xl p-6">
              <h3 className="font-bold mb-4 flex items-center gap-2 text-amber-500">
                <AlertTriangle className="w-5 h-5" />
                Doubt Zones
              </h3>
              <div className="space-y-4">
                {lecture.doubts.map((doubt, i) => (
                  <div key={i} className="text-sm">
                    <span className="text-xs font-mono text-amber-500 mb-1 block">{doubt.timestamp}</span>
                    <p className="text-gray-400">{doubt.reason}</p>
                  </div>
                ))}
              </div>
            </div>
          )}
        </div>
      </div>

      {/* Tabs */}
      <div className="border-b border-white/5 mb-8 flex gap-8">
        {[
          { id: 'notes', label: 'Study Notes', icon: FileText },
          { id: 'flashcards', label: 'Flashcards', icon: Zap },
          { id: 'quiz', label: 'Practice Quiz', icon: HelpCircle },
          { id: 'transcript', label: 'Transcript', icon: MessageSquare },
        ].map(tab => (
          <button 
            key={tab.id}
            onClick={() => setActiveTab(tab.id as any)}
            className={cn(
              "flex items-center gap-2 pb-4 px-2 font-semibold transition-all relative",
              activeTab === tab.id ? "text-indigo-400" : "text-gray-500 hover:text-gray-300"
            )}
          >
            <tab.icon className="w-5 h-5" />
            {tab.label}
            {activeTab === tab.id && (
              <motion.div 
                layoutId="activeTab"
                className="absolute bottom-0 left-0 right-0 h-0.5 bg-indigo-400"
              />
            )}
          </button>
        ))}
      </div>

      {/* Tab Content */}
      <div className="pb-20">
        <AnimatePresence mode="wait">
          {activeTab === 'notes' && (
            <motion.div 
              key="notes"
              initial={{ opacity: 0, y: 10 }}
              animate={{ opacity: 1, y: 0 }}
              exit={{ opacity: 0, y: -10 }}
              className="prose prose-invert prose-indigo max-w-none"
            >
              <div className="bg-[#141414] border border-white/5 rounded-3xl p-8 lg:p-12">
                <ReactMarkdown 
                  remarkPlugins={[remarkGfm, remarkMath]}
                  rehypePlugins={[rehypeKatex]}
                >
                  {lecture.detailedNotes || ''}
                </ReactMarkdown>
              </div>
            </motion.div>
          )}

          {activeTab === 'flashcards' && (
            <motion.div 
              key="flashcards"
              initial={{ opacity: 0, y: 10 }}
              animate={{ opacity: 1, y: 0 }}
              exit={{ opacity: 0, y: -10 }}
              className="grid grid-cols-1 md:grid-cols-2 gap-6"
            >
              {lecture.flashcards?.map((card, i) => (
                <div key={i} className="group h-64 [perspective:1000px]">
                  <div className="relative h-full w-full rounded-3xl transition-all duration-500 [transform-style:preserve-3d] group-hover:[transform:rotateY(180deg)]">
                    <div className="absolute inset-0 flex items-center justify-center p-8 bg-[#141414] border border-white/5 rounded-3xl [backface-visibility:hidden]">
                      <p className="text-xl font-bold text-center">{card.question}</p>
                    </div>
                    <div className="absolute inset-0 flex items-center justify-center p-8 bg-indigo-600 rounded-3xl [transform:rotateY(180deg)] [backface-visibility:hidden]">
                      <p className="text-xl font-bold text-center text-white">{card.answer}</p>
                    </div>
                  </div>
                </div>
              ))}
            </motion.div>
          )}

          {activeTab === 'quiz' && (
            <motion.div 
              key="quiz"
              initial={{ opacity: 0, y: 10 }}
              animate={{ opacity: 1, y: 0 }}
              exit={{ opacity: 0, y: -10 }}
              className="space-y-8"
            >
              {lecture.quiz?.map((q, i) => (
                <div key={i} className="bg-[#141414] border border-white/5 rounded-3xl p-8">
                  <h4 className="text-xl font-bold mb-6 flex gap-4">
                    <span className="text-indigo-400">Q{i+1}.</span>
                    {q.question}
                  </h4>
                  <div className="grid grid-cols-1 md:grid-cols-2 gap-4 mb-6">
                    {q.options.map((opt, j) => (
                      <button 
                        key={j}
                        className="p-4 rounded-2xl bg-white/5 border border-white/10 text-left hover:border-indigo-500/50 transition-all flex items-center justify-between group"
                      >
                        {opt}
                        <ChevronRight className="w-4 h-4 opacity-0 group-hover:opacity-100 transition-opacity" />
                      </button>
                    ))}
                  </div>
                  <details className="group">
                    <summary className="cursor-pointer text-indigo-400 font-semibold hover:underline list-none flex items-center gap-2">
                      View Answer & Explanation
                    </summary>
                    <div className="mt-4 p-6 bg-indigo-600/10 rounded-2xl border border-indigo-600/20">
                      <p className="font-bold text-indigo-400 mb-2">Correct Answer: {q.correctAnswer}</p>
                      <p className="text-gray-300">{q.explanation}</p>
                    </div>
                  </details>
                </div>
              ))}
            </motion.div>
          )}

          {activeTab === 'transcript' && (
            <motion.div 
              key="transcript"
              initial={{ opacity: 0, y: 10 }}
              animate={{ opacity: 1, y: 0 }}
              exit={{ opacity: 0, y: -10 }}
              className="bg-[#141414] border border-white/5 rounded-3xl p-8"
            >
              <div className="prose prose-invert max-w-none">
                <ReactMarkdown>{lecture.transcript || ''}</ReactMarkdown>
              </div>
            </motion.div>
          )}
        </AnimatePresence>
      </div>
    </motion.div>
  );
}
